### ISSUE TITLE
what's wrong then?

### ISSUE THREAD

**Issue by yanlee26** [ruyadorno/polymer-simple-slider#10]
`
$ bower install l2t-paper-slider
bower iron-component-page#^1.0.0           cached https://github.com/PolymerElements/iron-component-page.git#1.1.9
bower iron-component-page#^1.0.0         validate 1.1.9 against https://github.com/PolymerElements/iron-component-page.git#^1.0.0
bower                                     EINVRES Request to http://vm-8ca5-3314.nam.nsroot.net:9527/packages/l2t-paper-slider failed with 503

`

**Comment by ruyadorno** [comment]
I think you're asking at the wrong place, this project isn't **l2t-paper-slider** 😳
