### ISSUE TITLE
SimpleSlider 

### ISSUE THREAD

**Issue by LacikIgor** [ruyadorno/polymer-simple-slider#2]
Wanted to use this element inside another element.

Recieved this warning: A SimpleSlider main container elementshould have at least one child.

The images were displayed as native html images.

I am guessing your JS can't access shadow-dom elements :(

![simplesliderissue](https://cloud.githubusercontent.com/assets/3748583/5936305/725ad7ea-a6e3-11e4-8e36-b8eb3530ad6d.png)

**Comment by LacikIgor** [comment]
I located the bug and since I have no idea how to solve it (seems seriously shadow-dom :) ), posted a question on SO, hope you don't mind :)

http://stackoverflow.com/questions/28191102/access-children-of-a-custom-element-shadow-dom

**Comment by ruyadorno** [comment]
It seems it was just an url import error. Can I close this issue?

:relaxed:

**Comment by LacikIgor** [comment]
Yes,  sorry for bothering 0:)

One of the problems also was bower not being able to choose suitable
versions of dependencies, so that also resulted in my confusion,  but I
don't think you have to worry about that :$

**Comment by ruyadorno** [comment]
no problem! happy that you were able to fix it!

:+1:
