### ISSUE TITLE
Polymer V1

### ISSUE THREAD

**Issue by Link2Twenty** [ruyadorno/polymer-simple-slider#3]
Are you planning on moving this up to polymer V1?
If you do do this, it would be a good time add a components page too, which polymer examples.

Thanks
Andrew Bone

**Comment by ruyadorno** [comment]
polymer v1 support added on release **v1.0.0**

I haven't checked what a components page is yet but PRs are welcome 😄

**Comment by ruyadorno** [comment]
btw, I put the current `examples/` in a github pages website, it's accessible now on: http://ruyadorno.github.io/polymer-simple-slider/
